language: julia
os:
    - linux
    - osx
julia:
    - 0.6
    - 1.0
    - nightly
notifications:
    email: false

matrix:
  allow_failures:
  - julia: nightly

after_success:
    - julia -e 'VERSION >= v"0.7.0-DEV.5183" && using Pkg; Pkg.add("Coverage"); cd(Pkg.dir("SpecialMatrices")); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
