name = "SpecialMatrices"
uuid = "928aab9d-ef52-54ac-8ca1-acd7ca42c160"
version = "2.0.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"

[compat]
Polynomials = "1, 2, 3"
julia = "1.6"
